apiVersion: v1
kind: PersistentVolume
metadata:
  name: foo-pv
  namespace: ns-test
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
   - dir_mode=0700
   - file_mode=0600
   - vers=3.1.1
   - -uid=1001
   - gid=1001
csi:
   driver: smb.csi.k8s.io
   readonly: false
   volumeHandle: app-api-id # make sure its unquie in cluster 
   volumeAttributes:
    source: "//path.com/path/"
nodeStageSecretRef:
   name: name blabla
   namespace: ns-test 

