apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: custom-edit-pvc
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "watch", "list","create","update","patch","delete"]
  

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: custom-edit-role
rules:
- apiGroups: ["", "extensions","autoscaling","policy","apps","spv.no","networking.k8s.io","batch"] # "" indicates the core API group
  resources: ["pods","deployments","deployments/scale","replcasets",configmaps,services,horizantalpodaustoscaler, poddiscruptionbudgets,jobs,cronjobs]
  verbs: ["get", "watch", "list","create","update","patch","delete"]
  
  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: custom-view-role   ## cicd purpose
rules:
- apiGroups: ["", "extensions","autoscaling","policy","apps","spv.no","networking.k8s.io","batch"] # "" indicates the core API group
  resources: ["pods","deployments","deployments/scale","replcasets",configmaps,services,horizantalpodaustoscaler, poddiscruptionbudgets,jobs,cronjobs]
  verbs: ["get", "watch", "list"]
  
  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: custom-nsview-role
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["namespaces"]
  verbs: ["list"]
  
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: nsview-cluster-ClusterRoleBinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-nsview-role
subjects:
  - kind: Group
    name: system:authenticated
    apiGroup: rbac.authorization.k8s.io
